#!/usr/bin/env python3
"""
ood_domain.py -- build the out-of-distribution point cloud for one problem.

Shared by gen_ood_data.py (Feynman) and gen_ood_llmsrbench.py (LLM-SRBench).

Both methods translate the training box.  Variable j has training range
[l_j, r_j] with width W_j, and is displaced by offset_j * W_j, so offset_j is a
signed distance measured in that variable's own width.  They differ only in how
the offsets are chosen.

  legacy  offset_j = +k for every j, falling back to -k for every j, accepted only
          if a single draw of 3 * n_points candidates yields at least n_points // 2
          valid ones.  Reproduces the published datasets.  Loses 14 of the 210
          formulas at every gap >= 4, and lets a problem switch direction between
          one gap and the next.

  freeze  Per-variable gap kappa_j and direction s_j, with offset_j = s_j * kappa_j.
          Walking the gap ladder upward, each variable advances to the next k when
          the ground truth is still defined there and stays at its previous value
          when it is not; a variable that cannot advance in its current direction
          is offered the opposite one.  Loses nothing on either benchmark.

Under freeze, kappa_j <= k for every j and at least one variable reaches k, so gap
k means "every variable is outside its training range, and the furthest is k widths
out".  That is weaker than legacy's "every variable is exactly k widths out", and it
is what makes the formulas with a constrained domain representable at all: targets
like sqrt(E^2/p^2 - By^2 - Bz^2) need E and p far out while By and Bz stay near the
training range, since E/p is a ratio that stays flat as the box slides while
By^2 + Bz^2 grows with k.

Use build_region(); it covers both methods and reports the offsets each one chose.
"""

import numpy as np

METHODS = ("legacy", "freeze")

# Points per probe when measuring how much of a candidate box is valid.
PROBE_POINTS = 4096

# Fraction of a candidate box that must be valid before a variable is allowed to
# advance.  Not 1.0: collect() makes up the rest by drawing more candidates, and a
# lower bar lets variables advance further.
FEASIBLE_TARGET = 0.05

MIN_ROUND = 20_000
MAX_ROUND = 4_000_000
DEFAULT_BUDGET = 600_000_000


# ---------------------------------------------------------------------------
# Training-range geometry
# ---------------------------------------------------------------------------
def training_ranges(X_ref):
    """Per-variable (min, max, width) of the reference data.

    A variable whose values never change would have zero width and could never be
    displaced, so it is given width 1.0.  Neither benchmark currently contains one.
    """
    vmin = X_ref.min(axis=0)
    vmax = X_ref.max(axis=0)
    widths = np.where((vmax - vmin) < 1e-12, 1.0, vmax - vmin)
    return vmin, vmax, widths


def outside_distance(X, vmin, vmax, widths):
    """How far each coordinate lies outside its training range, in widths.

    Zero for coordinates inside the range.
    """
    return np.maximum(np.maximum(vmin - X, X - vmax), 0.0) / widths


def sample_box(vmin, vmax, widths, offsets, n, rng):
    """Training box displaced by offsets * widths, per variable.

    offsets is signed: -3.0 moves that variable three widths below its training
    range.  Both methods sample here; only the offsets differ.
    """
    shift = np.asarray(offsets, dtype = np.float64) * widths
    return rng.uniform(vmin + shift, vmax + shift, size = (n, len(widths)))


# ---------------------------------------------------------------------------
# Choosing the offsets
# ---------------------------------------------------------------------------
def _valid_fraction(evaluate, X):
    """Fraction of X where the ground truth is finite."""
    if len(X) == 0:
        return 0.0
    return float(np.isfinite(evaluate(X)).mean())


def _probe(evaluate, vmin, vmax, widths, offsets, rng, n=PROBE_POINTS):
    return _valid_fraction(evaluate, sample_box(vmin, vmax, widths, offsets, n, rng))


def gap_ladder(gap, gaps):
    """The gaps freeze walks through on its way to `gap`, ascending.

    Each gap is normally generated by a separate invocation, so the walk is replayed
    from the bottom every time rather than carried between runs.
    """
    ladder = sorted(g for g in gaps if 0 < g <= gap)
    if gap > 0 and (not ladder or ladder[-1] < gap):
        ladder.append(float(gap))
    return [float(g) for g in ladder]


def _walk(evaluate, vmin, vmax, widths, gap, gaps, seed, sign=None):
    """Walk the gap ladder up to `gap`, advancing each variable as far as it can go.

    At each rung, first try moving every variable together; if the ground truth is
    not defined there, advance them one at a time, in the order the benchmark lists
    them, keeping each advance that survives.  A variable that cannot advance stays
    at its previous value.

    With `sign` given, directions are fixed and only the gaps are chosen.  With
    `sign` None, a variable that cannot advance forward is offered the opposite
    direction, and the sign it settles on is returned.

    The one-at-a-time pass is order dependent: on 6 of the 111 LSR-Transform problems
    a different variable order freezes a different variable.  Every such choice is
    valid, but the result is not canonical, so the order is fixed to the benchmark's.
    """
    n_vars = len(widths)
    kappa = np.zeros(n_vars)
    directions = np.ones(n_vars) if sign is None else np.asarray(sign, dtype=np.float64).copy()
    rng = np.random.default_rng(seed)

    for k in gap_ladder(gap, gaps):
        together = np.full(n_vars, k)
        if _probe(evaluate, vmin, vmax, widths, directions * together, rng) >= FEASIBLE_TARGET:
            kappa = together
            continue

        for j in range(n_vars):
            advanced = kappa.copy()
            advanced[j] = k
            if _probe(evaluate, vmin, vmax, widths,
                      directions * advanced, rng) >= FEASIBLE_TARGET:
                kappa = advanced
                continue

            if sign is not None:
                continue                      # directions are fixed on this pass

            flipped = directions.copy()
            flipped[j] = -directions[j]
            if _probe(evaluate, vmin, vmax, widths,
                      flipped * advanced, rng) >= FEASIBLE_TARGET:
                kappa, directions = advanced, flipped

    return kappa, directions


def plan_freeze(evaluate, vmin, vmax, widths, gap, gaps, seed=0, positive_only=False):
    """Per-variable gap kappa and direction sign for one problem at one gap.

    Two passes.  The first walks the ladder to the largest gap and lets variables
    flip direction, which settles the sign.  The second walks to the requested gap
    with that sign held fixed.  Without the first pass a variable can advance
    forward at small gaps and only later discover it had to go the other way, so a
    problem would reverse direction partway along the gap axis; pinning removes that
    and costs nothing (checked: identical total advancement over all 888 LSR-Transform
    problem-gap pairs, no pair advancing less).

    positive_only keeps every variable moving in the +W direction, matching legacy's
    convention, and skips the settling pass since there is nothing to settle.  It
    loses no problem on either benchmark, but a variable whose domain lies only in
    the -W direction can then never advance and stays at kappa = 0 -- fully inside
    its training range at every gap.  That happens to 3 variables in 3 of the 111
    LSR-Transform problems (III.19.51_1_0, III.19.51_3_0, II.24.17_2_1), all of which
    need a negative input where the flip would have supplied one.

    kappa is non-decreasing in gap by construction, so a problem cannot move back
    toward its training range as the gap grows.

    Both passes use their own generator seeded from `seed` rather than the caller's,
    so the result is identical no matter which gap this process is generating.  Gaps
    are normally produced one per invocation, so the walk is replayed from the bottom
    each time rather than carried between runs.
    """
    if positive_only:
        return _walk(evaluate, vmin, vmax, widths, gap, gaps, seed,
                     sign=np.ones(len(widths)))

    settle_at = max(max(gaps), gap)
    _, sign = _walk(evaluate, vmin, vmax, widths, settle_at, gaps, seed)
    kappa, _ = _walk(evaluate, vmin, vmax, widths, gap, gaps, seed, sign=sign)
    return kappa, sign


def sample_legacy(evaluate, vmin, vmax, widths, gap, n_points, rng):
    """The original construction, reproduced exactly.

    One draw of 3 * n_points candidates in the all-positive direction; if fewer than
    max(10, n_points // 2) of them are valid, one draw in the all-negative direction;
    if that also falls short, the problem is dropped.

    That floor is what loses feynman_I_26_2, whose domain is a thin but usable
    sliver: at gap 4 it yields ~3400 good points and is discarded for not reaching
    5000.  The single global direction is what loses the other 13.

    Returns (X, y, sign), with sign the direction actually used, or empty arrays and
    None when both directions fail.
    """
    n_vars = len(widths)
    oversample = 3 * n_points

    for direction in (1.0, -1.0):
        sign = np.full(n_vars, direction)
        X = sample_box(vmin, vmax, widths, sign * gap, oversample, rng)
        y = evaluate(X)
        valid = np.isfinite(y)
        X_valid, y_valid = X[valid], y[valid]

        if len(X_valid) < max(10, n_points // 2):
            continue

        if len(X_valid) > n_points:
            keep = rng.choice(len(X_valid), size=n_points, replace=False)
            X_valid, y_valid = X_valid[keep], y_valid[keep]
        return X_valid, y_valid, sign

    return np.empty((0, n_vars)), np.empty(0), None


# ---------------------------------------------------------------------------
# Rejection sampling
# ---------------------------------------------------------------------------
def collect(sampler, evaluate, n_points, rng, budget=DEFAULT_BUDGET):
    """Draw until n_points valid points are collected or budget candidates are spent.

    Replaces the fixed 3x oversample with a 50%-acceptance floor that legacy still
    uses.  That floor discarded problems whose domain is a thin but usable sliver.

    Returns (X, y) with however many points were found, possibly zero.
    """
    kept_X, kept_y, found, drawn = [], [], 0, 0
    round_size = int(np.clip(4 * n_points, MIN_ROUND, MAX_ROUND))

    while found < n_points and drawn < budget:
        round_size = min(round_size, budget - drawn)
        X = sampler(round_size, rng)
        drawn += round_size

        if len(X):
            y = evaluate(X)
            valid = np.isfinite(y)
            if valid.any():
                kept_X.append(X[valid])
                kept_y.append(y[valid])
                found += int(valid.sum())

        # Size the next round from the yield so far: cheap regions finish in one
        # round, thin ones escalate instead of crawling.
        if found:
            need = n_points - found
            round_size = int(np.clip(1.5 * need * drawn / found, MIN_ROUND, MAX_ROUND))
        else:
            round_size = int(min(round_size * 4, MAX_ROUND))

    if not kept_X:
        return np.empty((0, 0)), np.empty(0)

    X = np.concatenate(kept_X)
    y = np.concatenate(kept_y)
    if len(X) > n_points:
        keep = rng.choice(len(X), size=n_points, replace=False)
        X, y = X[keep], y[keep]
    return X, y


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def build_region(method, evaluate, vmin, vmax, widths, gap, n_points, rng,
                 gaps=None, seed=0, budget=DEFAULT_BUDGET, positive_only=False):
    """Build one problem's OOD point cloud.

    Returns (X, y, kappa, sign).  Both methods are described by the same pair: the
    per-variable gap kappa and direction sign, whose product is the offset passed to
    sample_box.  legacy always has kappa_j = gap for every j.  X is empty when no
    valid points were found, which only legacy does.
    """
    n_vars = len(widths)

    if method == "legacy":
        X, y, sign = sample_legacy(evaluate, vmin, vmax, widths, gap, n_points, rng)
        kappa = np.full(n_vars, float(gap)) if sign is not None else None
        return X, y, kappa, sign

    if method == "freeze":
        kappa, sign = plan_freeze(evaluate, vmin, vmax, widths, gap,
                                  gaps or [gap], seed=seed,
                                  positive_only=positive_only)
        sampler = lambda n, r: sample_box(vmin, vmax, widths, sign * kappa, n, r)
        X, y = collect(sampler, evaluate, n_points, rng, budget)
        return X, y, kappa, sign

    raise ValueError(f"unknown method {method!r}; expected one of {METHODS}")


def describe(method, kappa, sign):
    """Short label for the chosen offsets, for logs and the payload."""
    if kappa is None or sign is None:
        return method
    if method == "legacy":
        return "legacy " + ("+" if sign[0] > 0 else "-")
    parts = ["kappa=" + ",".join(f"{int(k)}" for k in kappa)]
    if (sign < 0).any():
        parts.append("sign=" + "".join("-" if s < 0 else "+" for s in sign))
    return "freeze " + " ".join(parts)
